name: saas_new
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.36
  supabase_flutter: ^2.10.3
  razorpay_flutter: ^1.3.4
  google_sign_in: ^6.2.1
  flutter_markdown: ^0.6.18
  flutter_math_fork: ^0.7.2  # âœ… ADDED FOR LATEX RENDERING
  url_launcher: ^6.2.1
  intl: ^0.20.2
  http: ^1.2.0 
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  animate_do: ^4.2.0



flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
